#!/bin/sh
# /etc/init.d/paperwallet

### BEGIN INIT INFO
# Provides:          paperwallet
# Required-Start:    $all
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      6 1 0
# Short-Description: All services around paperwallet
# Description:       Based on /opt/paperwallet/conf/paperwallet.conf starts:  * DNSMASQ * HOSTAPD * DROOPY * WLAN-config * CHAT
### END INIT INFO
###
#  Default start-stop script for paperwallet services on a laptop
#   written by Matthias Strubel  (matthias.strubel@aod-rpg.de) 2011-02-22
#	adapted by sleepdeficit (simon@sleepdev.sh) 2017
#  licenced by gpl, feel free to improve and send me comments

[ -f /etc/default/rcS ] && . /etc/default/rcS

# PATH for /opt paperwallet folder
PATH=$PATH:/opt/paperwallet/bin

PIDFILE_HOSTAPN=/var/run/paperwallet_hostapn.pid
PIDFILE_DNSMASQ=/var/run/paperwallet_dnsmasq.pid
PIDFILE_LIGHTTPD=/opt/paperwallet/tmp/lighttpd.pid
PIDFILE_RADVD=/opt/paperwallet/tmp/radvd.pid

PAPERWALLET=/opt/paperwallet
CONF=$PAPERWALLET/conf/paperwallet.conf
CONF_IRC=$PAPERWALLET/conf/irc.conf
CONF_APN=$PAPERWALLET/conf/hostapd.conf

#Some extra config files for dnsmasq
CONF_DNSMASQ=$PAPERWALLET/conf/dnsmasq_generated.conf

CONF_RADVD=$PAPERWALLET/conf/radvd_generated.conf

CONF_LIGHTTPD=$PAPERWALLET/conf/lighttpd/lighttpd.conf

if [ -f $CONF ] ; then
   . $CONF
else
   echo "Configuration file not found"
   exit 1
fi

#If you can't find this file
if [[ -f $PAPERWALLET/conf/init_done ]] ; then
   INIT=OK
else
   $PAPERWALLET/bin/hooks/hook_pre_init.sh  "$CONF"
   $PAPERWALLET/bin/install_paperwallet.sh "$CONF" part2
   $PAPERWALLET/bin/hooks/hook_post_init.sh  "$CONF"
   touch   $PAPERWALLET/conf/init_done
fi

# Recreate the content folder, if it was deleted
#  only if it is not already existing.
#  This can be any time.
if [ ! -d  $WWW_CONTENT ] ; then
        $PAPERWALLET/bin/install_paperwallet.sh "$CONF" content
fi

# Command Line for DNSMASQ,  use extra config file generated from command above
CMD_DNSMASQ="-x $PIDFILE_DNSMASQ -C $CONF_DNSMASQ "

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script paperwallet "

    # Generate hosts & dnsmasq file
    $PAPERWALLET/bin/generate_config_files.sh  "$CONF"

    $PAPERWALLET/bin/hooks/hook_paperwallet_start.sh  "$CONF"

    if [ "$CUSTOM_DIRLIST_COPY" = "yes" ]; then
      echo "Copy over directory design files"
      $PAPERWALLET/bin/distribute_files.sh $SHARE_FOLDER/Shared
    fi

    if [ "$DO_IW" = "yes" ] ; then
       log_daemon_msg " Setting up Interface (iw) "
       iw $PHY_IF interface add $INTERFACE type managed
    fi

    if [ "$PROBE_INTERFACE" = "yes" ] ; then
      echo "  Probe wlan"
      #Setting up WLAN Interface
      paperwallet_setup_wlan.sh  $CONF probe
    fi
     if  [ $? -ne 0 ] ;  then
       echo "failed probing Interface"
     else

       # Only  activate
       if  [ "$USE_APN" =  "yes" ] ;  then
         echo  "Starting hostap... "
         start-stop-daemon -m -S -b -p $PIDFILE_HOSTAPN  -x /usr/sbin/hostapd --  $CONF_APN
         echo  $?
       fi

       if [ "$DO_IFCONFIG" = "yes" ] ; then
         echo "  Setting up wlan"
         #Setting up WLAN Interface
         paperwallet_setup_wlan.sh  $CONF start
         if  [ $? -ne 0 ] ;  then
          echo "failed setting up Interface"
          exit 255
         fi
      fi
      #BRIDGE
      if [ "$DO_BRIDGE" = "yes" ] ; then
         echo "Adding $INTERFACE to bridge $BRIDGE //  brctl addif $BRIDGE  $INTERFACE "
         sleep 1
         BR_CMD="brctl addif  $BRIDGE  $INTERFACE"
         ( $BR_CMD ; )
         if  [ $? -ne 0 ] ;  then
           echo "failed :( "
         fi
      fi

       if [ "$USE_DNSMASQ" = "yes" ] ;  then
         echo  "Starting dnsmasq... "
   # pidfile is written by dnsmasq
         start-stop-daemon -S -q -x /usr/sbin/dnsmasq  --  $CMD_DNSMASQ
         echo  $?
       fi


       echo  "Setting up firewall rules..."
       $PAPERWALLET_FOLDER/bin/firewall.sh -s
       echo $?

        if [ "$IPV6_ENABLE" = "yes" ] && [ "$IPV6_ADVERT" = "radvd" ] ; then
          echo  "Starting radvd..."
          start-stop-daemon  -S -q -x radvd  --  -p $PIDFILE_RADVD -C $CONF_RADVD
          echo $?
        fi

       #Start here the lighttpd i.e.
       echo "Starting lighttpd..."
       start-stop-daemon -S -q  -p $PIDFILE_LIGHTTPD -x /usr/sbin/lighttpd -- -f $CONF_LIGHTTPD
       echo $?

     fi

      $PAPERWALLET/bin/hooks/hook_paperwallet_start_done.sh  "$CONF"

    ;;
  stop)
    echo  "Stopping script paperwallet"

    $PAPERWALLET/bin/hooks/hook_paperwallet_stop.sh  "$CONF"

    if [  "$USE_APN"  = "yes" ] ;  then
       echo  "Stopping hostap... "
       start-stop-daemon -K  -q  -p $PIDFILE_HOSTAPN
       echo   $?
    fi
    if [ "$USE_DNSMASQ" = "yes" ] ;  then
       echo "Stopping dnsmasq..."
       start-stop-daemon -K  -q  -p $PIDFILE_DNSMASQ
       echo  $?
   fi


       echo  "Removing firewall rules..."
       $PAPERWALLET_FOLDER/bin/firewall.sh -k
       echo $?

     if [ -e $PIDFILE_RADVD ] ; then
        echo "Stopping radvd..."
        start-stop-daemon -K -q -p $PIDFILE_RADVD
        echo  $?
    fi

    echo "Stopping lighttpd..."
    start-stop-daemon -K -q -p $PIDFILE_LIGHTTPD
    echo $?

     if [ "$DO_IFCONFIG" = "yes" ] ; then
       paperwallet_setup_wlan.sh $CONF stop
     fi

     if [ "$DO_IW" = "yes" ] ; then
       iw dev $INTERFACE del
     fi

      #BRIDGE
      if [ "$DO_BRIDGE" = "yes" ] ; then
         echo "Remove  $INTERFACE to bridge $BRIDGE //  brctl addif
$BRIDGE  $INTERFACE "
         sleep 1
         BR_CMD="brctl delif  $BRIDGE  $INTERFACE"
         ( $BR_CMD ; )
         if  [ $? -ne 0 ] ;  then
           echo "failed :( "
         fi
      fi

      $PAPERWALLET/bin/hooks/hook_paperwallet_stop_done.sh  "$CONF"
      
    ;;
  *)
    echo "Usage: /etc/init.d/paperwallet {start|stop}"
    exit 1
    ;;
esac

exit 0
